import type {
  Appointment,
  Branch,
  Offer,
  QueueEntry,
  Service,
  User,
} from "./types";
import { addDaysISO, generateUserId, todayISO } from "./format";

const AVATAR_COLORS = [
  "#b08d57",
  "#5b7db1",
  "#7c9a78",
  "#a06b9c",
  "#c0794b",
  "#4f7a78",
  "#9c6b6b",
  "#6b6b9c",
];

export const seedBranches: Branch[] = [
  {
    id: "lhasurane",
    name: "Lhasurane",
    tagline: "Neighbourhood elegance, everyday glow.",
    address: "Shop 4, Lhasurane Main Road, Near City Bank",
    city: "Lhasurane",
    phone: "+91 98220 11223",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Glow+and+Glamour+Lhasurane",
    lat: 19.2183,
    lng: 72.9781,
    isOpen: true,
    availableChairs: 3,
    totalChairs: 4,
    workingHours: [
      { day: "Mon", open: "09:00", close: "20:00", closed: true },
      { day: "Tue", open: "09:00", close: "20:00" },
      { day: "Wed", open: "09:00", close: "20:00" },
      { day: "Thu", open: "09:00", close: "20:00" },
      { day: "Fri", open: "09:00", close: "20:00" },
      { day: "Sat", open: "09:00", close: "21:00" },
      { day: "Sun", open: "10:00", close: "18:00" },
    ],
  },
  {
    id: "koregaon",
    name: "Koregaon",
    tagline: "Full-service beauty & unisex salon.",
    address: "Plot 12, Koregaon Park Annexe, Lane 7",
    city: "Koregaon",
    phone: "+91 98220 44556",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Glow+and+Glamour+Koregaon",
    lat: 18.5362,
    lng: 73.8923,
    isOpen: true,
    availableChairs: 4,
    totalChairs: 6,
    workingHours: [
      { day: "Mon", open: "09:30", close: "21:00" },
      { day: "Tue", open: "09:30", close: "21:00" },
      { day: "Wed", open: "09:30", close: "21:00" },
      { day: "Thu", open: "09:30", close: "21:00" },
      { day: "Fri", open: "09:30", close: "21:00" },
      { day: "Sat", open: "09:00", close: "22:00" },
      { day: "Sun", open: "09:00", close: "20:00" },
    ],
  },
];

export const seedServices: Service[] = [
  // Lhasurane services (fewer)
  {
    id: "svc_lh_1",
    branchId: "lhasurane",
    category: "Haircuts",
    name: "Classic Haircut",
    price: 350,
    durationMin: 30,
    active: true,
  },
  {
    id: "svc_lh_2",
    branchId: "lhasurane",
    category: "Haircuts",
    name: "Premium Styling Cut",
    price: 650,
    durationMin: 45,
    active: true,
  },
  {
    id: "svc_lh_3",
    branchId: "lhasurane",
    category: "Hair Care",
    name: "Hair Spa & Nourish",
    price: 1200,
    durationMin: 60,
    active: true,
  },
  {
    id: "svc_lh_4",
    branchId: "lhasurane",
    category: "Hair Care",
    name: "Root Touch Up",
    price: 900,
    durationMin: 50,
    active: true,
  },
  {
    id: "svc_lh_5",
    branchId: "lhasurane",
    category: "Grooming",
    name: "Beard Trim & Shape",
    price: 250,
    durationMin: 20,
    active: true,
  },
  {
    id: "svc_lh_6",
    branchId: "lhasurane",
    category: "Styling",
    name: "Blow Dry & Finish",
    price: 400,
    durationMin: 30,
    active: false,
  },
  // Koregaon services (more, includes parlour/salon/beauty)
  {
    id: "svc_ko_1",
    branchId: "koregaon",
    category: "Haircuts",
    name: "Unisex Haircut",
    price: 450,
    durationMin: 35,
    active: true,
  },
  {
    id: "svc_ko_2",
    branchId: "koregaon",
    category: "Hair Care",
    name: "Keratin Smoothing",
    price: 3500,
    durationMin: 120,
    active: true,
  },
  {
    id: "svc_ko_3",
    branchId: "koregaon",
    category: "Ladies Parlour",
    name: "Bridal Makeup",
    price: 6500,
    durationMin: 150,
    active: true,
  },
  {
    id: "svc_ko_4",
    branchId: "koregaon",
    category: "Ladies Parlour",
    name: "Facial & Cleanup",
    price: 1500,
    durationMin: 60,
    active: true,
  },
  {
    id: "svc_ko_5",
    branchId: "koregaon",
    category: "Beauty Services",
    name: "Manicure & Pedicure",
    price: 1800,
    durationMin: 75,
    active: true,
  },
  {
    id: "svc_ko_6",
    branchId: "koregaon",
    category: "Beauty Services",
    name: "Waxing (Full Arms)",
    price: 800,
    durationMin: 40,
    active: true,
  },
  {
    id: "svc_ko_7",
    branchId: "koregaon",
    category: "Unisex Salon",
    name: "Hair Colour Global",
    price: 2800,
    durationMin: 90,
    active: true,
  },
  {
    id: "svc_ko_8",
    branchId: "koregaon",
    category: "Unisex Salon",
    name: "Head Massage & Wash",
    price: 500,
    durationMin: 25,
    active: true,
  },
  {
    id: "svc_ko_9",
    branchId: "koregaon",
    category: "Beauty Services",
    name: "Eyebrow Threading",
    price: 150,
    durationMin: 15,
    active: true,
  },
];

export const seedOffers: Offer[] = [
  {
    id: "off_1",
    branchId: "lhasurane",
    title: "Monday Glow Deal",
    description: "20% off on all Hair Spa treatments every Monday.",
    badge: "20% OFF",
    active: true,
    startsAt: addDaysISO(-10),
    endsAt: addDaysISO(20),
  },
  {
    id: "off_2",
    branchId: "koregaon",
    title: "Bridal Season Package",
    description: "Book Bridal Makeup + Facial and save ₹1500.",
    badge: "SAVE ₹1500",
    active: true,
    startsAt: addDaysISO(-5),
    endsAt: addDaysISO(40),
  },
  {
    id: "off_3",
    branchId: "all",
    title: "First Visit Bonus",
    description: "New customers get 15% off their first appointment.",
    badge: "15% OFF",
    active: true,
    startsAt: addDaysISO(-30),
    endsAt: addDaysISO(60),
  },
  {
    id: "off_4",
    branchId: "koregaon",
    title: "Weekend Wax Saver",
    description: "Flat ₹200 off full-arms waxing on weekends.",
    badge: "₹200 OFF",
    active: false,
    startsAt: addDaysISO(-2),
    endsAt: addDaysISO(15),
  },
];

const FIXED_IDS = [
  "GG7K4M9P2Q",
  "GG2S8N1L5X",
  "GG3R5D7H9C",
  "GG4K1V6N8B",
  "GG6I2M4S7T",
  "GG8P3Y9A1D",
  "GG9A6J2E5F",
  "GG5M7K3R8W",
  "GG1C9N4V6L",
  "GG2T5B8Q3Z",
];

function makeUser(
  i: number,
  data: Partial<User> & Pick<User, "fullName" | "phone" | "email" | "password" | "preferredBranch" | "role">
): User {
  return {
    id: FIXED_IDS[i] ?? generateUserId(),
    avatarColor: AVATAR_COLORS[i % AVATAR_COLORS.length],
    createdAt: addDaysISO(-((i * 11) % 110) - 5),
    active: true,
    ...data,
  };
}

export const seedUsers: User[] = [
  makeUser(0, {
    fullName: "Aarav Mehta",
    phone: "+91 90000 10001",
    email: "owner@glowglamour.com",
    password: "owner123",
    preferredBranch: "koregaon",
    role: "owner",
    ownerBranch: "koregaon",
    avatarColor: "#b08d57",
  }),
  makeUser(1, {
    fullName: "Sneha Patil",
    phone: "+91 90000 20002",
    email: "sneha@staff.com",
    password: "staff123",
    preferredBranch: "lhasurane",
    role: "staff",
    staffBranch: "lhasurane",
    staffPosition: "Senior Stylist",
    staffServices: ["svc_lh_1", "svc_lh_2", "svc_lh_3"],
    active: true,
  }),
  makeUser(2, {
    fullName: "Rohan Deshmukh",
    phone: "+91 90000 20003",
    email: "rohan@staff.com",
    password: "staff123",
    preferredBranch: "lhasurane",
    role: "staff",
    staffBranch: "lhasurane",
    staffPosition: "Hair Expert",
    staffServices: ["svc_lh_4", "svc_lh_5"],
    active: true,
  }),
  makeUser(3, {
    fullName: "Kavya Nair",
    phone: "+91 90000 20004",
    email: "kavya@staff.com",
    password: "staff123",
    preferredBranch: "koregaon",
    role: "staff",
    staffBranch: "koregaon",
    staffPosition: "Beauty Therapist",
    staffServices: ["svc_ko_3", "svc_ko_4", "svc_ko_5"],
    active: true,
  }),
  makeUser(4, {
    fullName: "Imran Sheikh",
    phone: "+91 90000 20005",
    email: "imran@staff.com",
    password: "staff123",
    preferredBranch: "koregaon",
    role: "staff",
    staffBranch: "koregaon",
    staffPosition: "Master Stylist",
    staffServices: ["svc_ko_1", "svc_ko_7", "svc_ko_8"],
    active: true,
  }),
  makeUser(5, {
    fullName: "Priya Sharma",
    phone: "+91 90000 30006",
    email: "priya@example.com",
    password: "cust123",
    preferredBranch: "lhasurane",
    role: "customer",
  }),
  makeUser(6, {
    fullName: "Aditya Joshi",
    phone: "+91 90000 30007",
    email: "aditya@example.com",
    password: "cust123",
    preferredBranch: "koregaon",
    role: "customer",
  }),
  makeUser(7, {
    fullName: "Meera Kapoor",
    phone: "+91 90000 30008",
    email: "meera@example.com",
    password: "cust123",
    preferredBranch: "koregaon",
    role: "customer",
  }),
  makeUser(8, {
    fullName: "Karan Verma",
    phone: "+91 90000 30009",
    email: "karan@example.com",
    password: "cust123",
    preferredBranch: "lhasurane",
    role: "customer",
  }),
  makeUser(9, {
    fullName: "Sara Thomas",
    phone: "+91 90000 30010",
    email: "sara@example.com",
    password: "cust123",
    preferredBranch: "koregaon",
    role: "customer",
  }),
];

export const seedAppointments: Appointment[] = [
  {
    id: "appt_1",
    reference: "GG-AB12CD",
    customerId: seedUsers[5].id,
    customerName: "Priya Sharma",
    customerPhone: "+91 90000 30006",
    branchId: "lhasurane",
    serviceIds: ["svc_lh_3"],
    date: todayISO(),
    time: "10:30",
    status: "confirmed",
    isWalkIn: false,
    token: 1,
    createdAt: addDaysISO(-1),
    assignedStaffId: seedUsers[1].id,
  },
  {
    id: "appt_2",
    reference: "GG-EF34GH",
    customerId: seedUsers[8].id,
    customerName: "Karan Verma",
    customerPhone: "+91 90000 30009",
    branchId: "lhasurane",
    serviceIds: ["svc_lh_1"],
    date: todayISO(),
    time: "11:15",
    status: "checked_in",
    isWalkIn: false,
    token: 2,
    createdAt: addDaysISO(-1),
    assignedStaffId: seedUsers[2].id,
  },
  {
    id: "appt_3",
    reference: "GG-IJ56KL",
    customerId: "walkin_lh",
    customerName: "Walk-in Guest",
    customerPhone: "—",
    branchId: "lhasurane",
    serviceIds: ["svc_lh_2"],
    date: todayISO(),
    time: "11:40",
    status: "checked_in",
    isWalkIn: true,
    token: 3,
    createdAt: addDaysISO(0),
  },
  {
    id: "appt_4",
    reference: "GG-MN78OP",
    customerId: seedUsers[6].id,
    customerName: "Aditya Joshi",
    customerPhone: "+91 90000 30007",
    branchId: "koregaon",
    serviceIds: ["svc_ko_1"],
    date: todayISO(),
    time: "12:00",
    status: "confirmed",
    isWalkIn: false,
    token: 1,
    createdAt: addDaysISO(-2),
    assignedStaffId: seedUsers[4].id,
  },
  {
    id: "appt_5",
    reference: "GG-QR90ST",
    customerId: seedUsers[7].id,
    customerName: "Meera Kapoor",
    customerPhone: "+91 90000 30008",
    branchId: "koregaon",
    serviceIds: ["svc_ko_4", "svc_ko_9"],
    date: todayISO(),
    time: "13:30",
    status: "in_service",
    isWalkIn: false,
    token: 2,
    createdAt: addDaysISO(-2),
    assignedStaffId: seedUsers[3].id,
  },
  {
    id: "appt_6",
    reference: "GG-UV12WX",
    customerId: seedUsers[5].id,
    customerName: "Priya Sharma",
    customerPhone: "+91 90000 30006",
    branchId: "koregaon",
    serviceIds: ["svc_ko_7"],
    date: addDaysISO(1),
    time: "15:00",
    status: "pending",
    isWalkIn: false,
    token: null,
    createdAt: addDaysISO(0),
  },
  {
    id: "appt_7",
    reference: "GG-YZ34AB",
    customerId: seedUsers[9].id,
    customerName: "Sara Thomas",
    customerPhone: "+91 90000 30010",
    branchId: "koregaon",
    serviceIds: ["svc_ko_3"],
    date: addDaysISO(2),
    time: "10:00",
    status: "confirmed",
    isWalkIn: false,
    token: null,
    createdAt: addDaysISO(-1),
    assignedStaffId: seedUsers[3].id,
  },
  {
    id: "appt_8",
    reference: "GG-CD56EF",
    customerId: seedUsers[8].id,
    customerName: "Karan Verma",
    customerPhone: "+91 90000 30009",
    branchId: "lhasurane",
    serviceIds: ["svc_lh_5"],
    date: addDaysISO(1),
    time: "17:30",
    status: "pending",
    isWalkIn: false,
    token: null,
    createdAt: addDaysISO(0),
  },
];

export const seedQueue: Record<string, QueueEntry[]> = {
  lhasurane: [
    { token: 2, appointmentId: "appt_2", customerName: "Karan Verma", branchId: "lhasurane", isWalkIn: false, joinedAt: addDaysISO(0) },
    { token: 3, appointmentId: "appt_3", customerName: "Walk-in Guest", branchId: "lhasurane", isWalkIn: true, joinedAt: addDaysISO(0) },
  ],
  koregaon: [
    { token: 2, appointmentId: "appt_5", customerName: "Meera Kapoor", branchId: "koregaon", isWalkIn: false, joinedAt: addDaysISO(0) },
  ],
};

export const seedNotifications: never[] = [];
